# Generated by Django 4.1.1 on 2022-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='status_product',
            field=models.BooleanField(default=1, verbose_name='Статус продукта'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StatusProduct',
        ),
    ]
