# Generated by Django 4.1.1 on 2022-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_status_product_status_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status_product',
            field=models.BooleanField(default=False, verbose_name='Статус продукта'),
        ),
    ]
