# Generated by Django 4.1.1 on 2022-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activity_product',
            field=models.BooleanField(default=True, verbose_name='Активность продукта'),
        ),
    ]
