# Generated by Django 4.1.1 on 2022-09-27 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Идентификатор чата')),
                ('chat_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_chat', to='products.product', verbose_name='Продукт')),
                ('from_chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('to_chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_chat', to=settings.AUTH_USER_MODEL, verbose_name='К пользователю')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
    ]
