# Generated by Django 4.1.1 on 2022-10-05 04:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c0f2846-50d2-4108-96ba-eeffd66b5788'), editable=False, primary_key=True, serialize=False),
        ),
    ]
