# Generated by Django 4.1.1 on 2022-09-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=100, verbose_name='Телефонный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profile_image/', verbose_name='Фотография профиля'),
            preserve_default=False,
        ),
    ]
