# Generated by Django 4.1.1 on 2022-09-21 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_wallet_alter_user_id_delete_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(default=uuid.uuid4, max_length=150, verbose_name='Кошелек'),
        ),
    ]
