# Generated by Django 4.1.1 on 2022-09-21 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(default=uuid.uuid4, max_length=150, unique=True, verbose_name='Кошелек'),
        ),
    ]
