# Generated by Django 4.1.1 on 2022-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/no_image.png', null=True, upload_to='profile_image/', verbose_name='Фотография профиля'),
        ),
    ]
