# Generated by Django 4.1.1 on 2022-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_wallet', models.CharField(max_length=150, verbose_name='Адрес кошелька')),
                ('amount_money', models.PositiveIntegerField(verbose_name='Сумма кошелька')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
