# Generated by Django 4.1.1 on 2022-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Баланс пользователя'),
        ),
    ]
