# Generated by Django 4.1.1 on 2022-09-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_moneytransfer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_notification',
            field=models.BooleanField(default=False, verbose_name='Уведомления от чатов'),
        ),
    ]
