# Generated by Django 4.1.1 on 2022-09-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_message_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneytransfer',
            options={'verbose_name': 'Перевод денег', 'verbose_name_plural': 'Переводы денег'},
        ),
    ]
