# Generated by Django 4.1.1 on 2022-09-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу linkedin'),
        ),
    ]
