# Generated by Django 4.1.1 on 2022-09-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
