# Generated by Django 4.1.1 on 2022-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status_contact',
            field=models.BooleanField(default=False, verbose_name='Статус обращения'),
        ),
    ]
