# Generated by Django 4.1.1 on 2022-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта сайта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефонный номер'),
        ),
    ]
